apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: tanzu-java-web-app-tim-id-pw
  annotations: {}
  labels:
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-java-web-app
spec:
  name: tim-id-pw
  service:
    apiVersion: v1
    kind: Secret
    name: tim-secret
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: tanzu-java-web-app

