apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: tanzu-java-web-app-tim-tim-id-pw
  annotations: {}
  labels:
    app.kubernetes.io/part-of: tanzu-java-web-app-tim
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-java-web-app-tim
spec:
  name: tim-id-pw
  service:
    apiVersion: v1
    kind: Secret
    name: tim-secret
  workload:
    apiVersion: apps/v1
    kind: Deployment
    name: tanzu-java-web-app-tim

